chat_app/urls.py
from django.urls import path
from .views import ChatPage

app_name = 'chat_app'

urlpatterns = [
    path('', ChatPage.as_view(), name='chat_page'),
]

movie_service/urls.py
from django.contrib import admin
from django.urls import path, include
from user_app import views as user_views
from rating_app import views as rating_views

from rating_app.views import StartPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', StartPage.as_view(), name='index_page'),
    path('chat/', include('chat_app.urls', namespace='chat')),
    path('users/', include('user_app.urls', namespace='users')),
    path('movies/', include('rating_app.urls', namespace='movies')),
    path('wishlist/', include('wishlist_app.urls', namespace='wishlists'))
]

user_app/urls.py
from django.urls import path
from .views import RegisterUser, LoginUser, LogoutUser

app_name = 'user_app'

urlpatterns = [
    path('register/', RegisterUser.as_view(), name='register_page'),
    path('login/', LoginUser.as_view(), name='login_page'),
    path('logout/', LogoutUser.as_view(), name='logout'),
]

user_app/models.py
from django.db import models

# Create your models here.

user_app/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(label='', max_length=50, widget=forms.TextInput(attrs={'class': "form-field",
                                                                                      'placeholder': "Логин"}))

    email = forms.EmailField(label='', max_length=100, widget=forms.TextInput(attrs={'class': "form-field",
                                                                                     'placeholder': "Email"}))

    password1 = forms.CharField(label='', widget=(forms.PasswordInput(attrs={'class': "form-field",
                                                                             'placeholder': "Пароль"})))

    password2 = forms.CharField(label='', widget=(forms.PasswordInput(attrs={'class': "form-field",
                                                                             'placeholder': "Повторите пароль"})))

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email", "password1", "password2")
        help_texts = {
            'password': None
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError("Passwords don't match.")
        return cd['password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='', max_length=50, widget=forms.TextInput(attrs={'class': "form-field",
                                                                                      'placeholder': "Логин"}))

    password = forms.CharField(label='', widget=(forms.PasswordInput(attrs={'class': "form-field",
                                                                            'placeholder': "Пароль"})))

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "password")
        help_texts = {
            'password': None
        }

user_app/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy
from django.contrib import auth
from django.views import View
from django.views.generic import CreateView, FormView

from .forms import RegisterForm, LoginForm


# Create your views here.
class RegisterUser(CreateView):
    template_name = 'register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('user_app:login_page')


class LoginUser(FormView):
    template_name = 'login.html'
    form_class = LoginForm
    success_url = reverse_lazy('index_page')

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            username: str = request.POST['username']
            password: str = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse_lazy('index_page'))
        return self.form_invalid(form)


class LogoutUser(View):
    def get(self, request):
        auth.logout(request)
        return HttpResponseRedirect(reverse_lazy('index_page'))

user_app/templates/user_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{% static 'user_app/css/style.css' %}">
    <title>Movier</title>
</head>
<body>

{% block welcome_page %}
{% endblock %}

{% block login_page %}
{% endblock %}

{% block register_page %}
{% endblock %}

{% block rating_page %}
{% endblock %}

<script src="{% static 'js/script.js'%}"></script>
</body>
</html>

user_app/templates/user_app/login.html
{% extends 'user_app/base.html' %}
{% block login_page %}
<main class="main">
    <div class="wrapper">
        <div class="container">
            <div class="title">
                <h2>Войдите в аккаунт</h2>
            </div>
            <form action="{% url 'user_app:login_page' %}" method="POST">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="form-btn">
                    <div>Войти</div>
                </button>
            </form>
            <span>у вас нет аккаунта, <a class="account" href="{% url 'user_app:register_page' %}">зарегистрируйтесь</a></span>
        </div>
    </div>
</main>
{% endblock %}

user_app/templates/user_app/register.html
{% extends 'user_app/base.html' %}
{% block register_page %}
<main class="main">
    <div class="wrapper">
        <div class="container">
            <div class="title">
                <h2>Создать аккаунт</h2>
            </div>
            <form action="{% url 'user_app:register_page' %}" method="POST">
                {% csrf_token%}
                {{ form }}
                <button type="submit" class="form-btn">
                    <div>Sign up</div>
                </button>
            </form>
            <span>уже есть аккаунт, <a class="account" href="{% url 'user_app:login_page' %}">войдите</a></span>
        </div>
    </div>
</main>
{% endblock %}