chat_app/urls.py
from django.urls import path
from .views import ChatPage

app_name = 'chat_app'

urlpatterns = [
    path('', ChatPage.as_view(), name='chat_page'),
]

movie_service/urls.py
from django.contrib import admin
from django.urls import path, include
from user_app import views as user_views
from rating_app import views as rating_views

from rating_app.views import StartPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', StartPage.as_view(), name='index_page'),
    path('chat/', include('chat_app.urls', namespace='chat')),
    path('users/', include('user_app.urls', namespace='users')),
    path('movies/', include('rating_app.urls', namespace='movies')),
    path('wishlist/', include('wishlist_app.urls', namespace='wishlists'))
]

rating_app/urls.py
from django.urls import path
from .views import ShowRating, CreateRating, ChooseMovie, AddId

app_name = 'rating_app'

urlpatterns = [
    path('rating', ShowRating.as_view(), name='rating_page'),
    path('rating/create', CreateRating.as_view(), name='create_page'),
    path('rating/choose', ChooseMovie.as_view(), name='choose_page'),
    path('rating/choose/id', AddId.as_view(), name='add_id_page')
]

rating_app/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=50, verbose_name='Title')

    year = models.CharField(max_length=4, verbose_name='Year')

    link = models.CharField(max_length=150, verbose_name='Link')

    kp_rating = models.FloatField(verbose_name='KP-Rating')

    rating = models.FloatField(verbose_name='Your rating')

    movie_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='user'
    )

    def __str__(self) -> str:
        return f'{self.title}'

rating_app/forms.py
from django import forms

from rating_app.models import Movie


class CreationForm(forms.ModelForm):
    title = forms.CharField(label='', max_length=100, widget=forms.TextInput(attrs={'class': "form-field",
                                                                                    'placeholder': "Title"}))

    rating = forms.IntegerField(label='', widget=forms.TextInput(attrs={'class': "rating-field",
                                                                        'type': 'range',
                                                                        'min': '0',
                                                                        'max': '10',
                                                                        'step': '0.5',
                                                                        'value': '0'}))

    class Meta:
        model = Movie
        fields = ['title', 'rating']


class AddIdForm(forms.Form):
    id = forms.IntegerField(label='', widget=forms.TextInput(attrs={'class': "form-field",
                                                                    'placeholder': "id"}))

rating_app/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse
from django.shortcuts import HttpResponseRedirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, ListView,FormView

from .decorators import rate_film_required

from .models import Movie
from .forms import CreationForm, AddIdForm
from .utils import get_films_data, get_film_by_id, FILM


class StartPage(TemplateView):
    template_name = 'index.html'


@method_decorator(login_required(login_url='users:login_page'), name='dispatch')
class ShowRating(ListView):
    model = Movie
    template_name = 'marks.html'

    def get_queryset(self):
        user = self.request.user
        ordering = self.request.GET.get('order', 'title')
        object_list = Movie.objects.filter(movie_user=user).order_by(ordering)

        items_per_page = 10

        paginator = Paginator(object_list, items_per_page)

        page = self.request.GET.get('page')

        try:
            objects = paginator.page(page)
        except PageNotAnInteger:
            objects = paginator.page(1)
        except EmptyPage:
            objects = paginator.page(paginator.num_pages)
        return objects

    def post(self, request):
        action = request.POST.get('action')
        if action == 'update':
            movie_id = int(request.POST.get('film'))
            new_rating = float(request.POST.get('new_rating'))
            movie = get_object_or_404(Movie, pk=movie_id)
            movie.rating = new_rating
            movie.save()
        elif action == 'delete':
            movie_id = int(request.POST.get('film'))
            movie = get_object_or_404(Movie, pk=movie_id)
            movie.delete()

        return HttpResponseRedirect(reverse_lazy('movies:rating_page'))


class CreateRating(FormView):
    template_name = 'create_mark.html'
    form_class = CreationForm

    def post(self, request, *args, **kwargs):
        title: str = request.POST['title']
        rating: str = request.POST['rating']
        return HttpResponseRedirect(reverse_lazy('movies:choose_page') + f'?title={title}&rating={rating}')


@method_decorator(rate_film_required, name='dispatch')
@method_decorator(login_required(login_url='users:login_page'), name='dispatch')
class ChooseMovie(TemplateView):
    template_name = 'choose_movie.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        rating: str = self.request.GET.get('rating')
        title: str = self.request.GET.get('title')
        context['films_data'] = get_films_data(title)
        context['rating'] = rating
        return context

    def post(self, request, *args, **kwargs):
        rating: float = float(request.POST.get('rating'))
        try:
            movie_id: int = int(request.POST.get('film'))
        except TypeError:
            return HttpResponse('<h1>Фильм с таким названием не найдем</h1>')

        movie_data: FILM = get_film_by_id(movie_id)
        user: str = request.user
        Movie.objects.create(title=movie_data.ru_name, year=movie_data.year, link=movie_data.kp_url,
                             kp_rating=movie_data.kp_rate,
                             rating=rating, movie_user=user)
        return HttpResponseRedirect(reverse_lazy('movies:rating_page'))


class AddId(FormView):
    template_name = 'add_id.html'
    form_class = AddIdForm
    success_url = 'movies:rating_page'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rating'] = self.request.GET.get('rating')
        return context

    def post(self, request, *args, **kwargs):
        rating: int = self.request.POST.get('rating')
        movie_id: int = self.request.POST.get('id')
        user: str = self.request.user

        try:
            movie_data: FILM = get_film_by_id(movie_id)
        except:
            return HttpResponse('<h1>Фильм с таким id не найдем</h1>')

        Movie.objects.create(title=movie_data.ru_name, year=movie_data.year, link=movie_data.kp_url,
                             kp_rating=movie_data.kp_rate,
                             rating=rating, movie_user=user)
        return HttpResponseRedirect(reverse_lazy('movies:rating_page'))

rating_app/templates/rating_app/add_id.html
{% extends 'rating_app/base.html' %}
{% load static %}
{% block rating_page %}
<section class="wrapper">
    <h1 class="movie-header">Добавить новый фильм!{{ rating }}</h1>
    <form class="create_rating" action="{% url 'movies:add_id_page' %}" method="post">
        {% csrf_token %}
        <div class="range-container">
             <input style="display: none;" type="text" name="rating" value="{{rating}}">
            {{form}}
        </div>
        <button type="submit">Добавить</button>
    </form>
</section>
{% endblock %}

rating_app/templates/rating_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{% static 'rating_app/css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <title>Movier</title>
</head>
<body>

{% block rating_page %}
{% endblock %}

{% block create_page %}
{% endblock %}

<script src="{% static 'js/script.js'%}"></script>
</body>
</html>

rating_app/templates/rating_app/choose_movie.html
{% extends 'rating_app/base.html' %}
{% load static %}
{% block rating_page %}
<section class="wrapper">
    <h1 class="movie-header">Выберите нужный фильм</h1>
    <a class="go_back" href="{% url 'movies:rating_page' %}">Вернуться</a>
    <form class="choose-form" action="{% url 'movies:choose_page' %}" method="post">
        {% csrf_token %}
        <input style="display: none;" type="text" name="rating" value="{{rating}}">
        <div class="main-table">
            <div class="tbl-header">
                <table>
                    <thead>
                        <tr>
                            <th>Постер</th>
                            <th>Фильм</th>
                            <th>Год</th>
                            <th>Ссылка</th>
                        </tr>
                    </thead>
                </table>
            </div>
            <div class="tbl-content">
                <table>
                    <tbody>

                    {% for item in films_data %}
                        <tr>
                            <td>
                                <img src="{{item.poster_preview}}" alt="poster">
                            </td>
                            <td>
                                <input type="radio" name="film" value="{{item.kp_id}}">
                                <label for="film">{{item.ru_name}}</label>
                            </td>
                            <td>{{item.year}}</td>
                            <td><a class="movie-link" href="{{item.kp_url}}">Click</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="options">
            <div class="update-btn">
                <button type="submit">Выбрать фильм</button>
            </div>
            <div class="choose_id">
                <a class="go_back" href="{% url 'movies:add_id_page' %}?rating={{rating}}">Найти по id</a>
            </div>
        </div>
        </iframe>
    </form>
</section>
{% endblock %}

rating_app/templates/rating_app/create_mark.html
{% extends 'rating_app/base.html' %}
{% load static %}
{% block create_page %}
<section class="wrapper">
    <h1 class="movie-header">Оценить фильм</h1>
    <form class="create_rating" action="{% url 'movies:create_page' %}" method="post">
        {% csrf_token %}
        <div class="range-container">
            {{form}}
            <div id="h4-container">
                <div id="h4-subcontainer">
                    <h4>0
                        <span></span>
                    </h4>
                </div>
            </div>
        </div>
        <button type="submit">Добавить</button>
    </form>
</section>
{% endblock %}

rating_app/templates/rating_app/marks.html
{% extends 'rating_app/base.html' %}
{% load static %}
{% block rating_page %}
<section class="wrapper">
    <h1 class="movie-header">Рейтинг</h1>
    <div  class="movie-menu">
        <form action="{% url 'movies:rating_page' %}" method="GET" class="sorting-form">
            <span>Sorting by: </span>
            <div>
                <ul class="sorting-menu">
                    <li>[ASC]</li>
                    <li><input type="submit" name="order" value="title" class="sort-item"></li>
                    <li><input type="submit" name="order" value="year" class="sort-item"></li>
                    <li><input type="submit" name="order" value="rating" class="sort-item"></li>
                </ul>
                <ul class="sorting-menu">
                    <li>[DESC]</li>
                    <li><input type="submit" name="order" value="-title" class="sort-item"></li>
                    <li><input type="submit" name="order" value="-year" class="sort-item"></li>
                    <li><input type="submit" name="order" value="-rating" class="sort-item"></li>
                </ul>
            </div>
        </form>
        <div>
            <a class="go_back" href="{% url 'index_page' %}">Вернуться</a>
            <a class="rate_new" href="{% url 'movies:create_page' %}">Оценить фильм</a>
        </div>
    </div>
    <form action="{% url 'movies:rating_page' %}" method="post">
        {% csrf_token %}
        <div class="main-table">
            <div class="tbl-header">
                <table>
                    <thead>
                        <tr>
                            <th>Фильм</th>
                            <th>Год</th>
                            <th>Ссылка</th>
                            <th>Рейтинг</th>
                            <th>Оценка</th>
                        </tr>
                    </thead>
                </table>
            </div>
            <div class="tbl-content">
                <table>
                    <tbody>
                    {% for item in object_list %}
                        <tr>
                            <td>
                                <input class="" type="radio" name="film" value="{{item.pk}}">
                                <label for="film">{{item.title}}</label>
                            </td>
                            <td>{{item.year}}</td>
                            <td><a class="movie-link" href="{{item.link}}">Click</a></td>
                            <td>{{item.kp_rating}}</td>
                            <td>{{item.rating}}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    <div class="pagination">
        <span class="step-links">
            {% if object_list.has_previous %}
                <a href="?page=1"><b> << </b></a>
                <a href="?page={{ object_list.previous_page_number }}"><b><</b></a>
            {% endif %}

            <span class="current">
                Страница {{ object_list.number }} из {{ object_list.paginator.num_pages }}
            </span>

            {% if object_list.has_next %}
                <a href="?page={{ object_list.next_page_number }}"><b> > </b></a>
                <a href="?page={{ object_list.paginator.num_pages }}"><b> >> </b></a>
            {% endif %}
        </span>
    </div>
        <div class="update-btn">
            <div class="update-rating">
                <h3>Измените оценку</h3>
                <input name="new_rating" type="range" value="0" min="0" max="10" step="0.5">
                <div id="h4-container">
                    <div id="h4-subcontainer">
                        <h4>0
                            <span></span>
                        </h4>
                    </div>
                </div>
            </div>
            <button type="submit" name="action" value="update">Обновить</button>
            <button type="submit" name="action" value="delete">Удалить</button>
        </div>
    </form>
</section>
{% endblock %}