chat_app/urls.py
from django.urls import path
from .views import ChatPage

app_name = 'chat_app'

urlpatterns = [
    path('', ChatPage.as_view(), name='chat_page'),
]

movie_service/urls.py
from django.contrib import admin
from django.urls import path, include
from user_app import views as user_views
from rating_app import views as rating_views

from rating_app.views import StartPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', StartPage.as_view(), name='index_page'),
    path('chat/', include('chat_app.urls', namespace='chat')),
    path('users/', include('user_app.urls', namespace='users')),
    path('movies/', include('rating_app.urls', namespace='movies')),
    path('wishlist/', include('wishlist_app.urls', namespace='wishlists'))
]

user_app/urls.py
from django.urls import path
from .views import RegisterUser, LoginUser, LogoutUser

app_name = 'user_app'

urlpatterns = [
    path('register/', RegisterUser.as_view(), name='register_page'),
    path('login/', LoginUser.as_view(), name='login_page'),
    path('logout/', LogoutUser.as_view(), name='logout'),
]

chat_app/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView


# Create your views here.
@method_decorator(login_required(login_url='users:login_page'), name='dispatch')
class ChatPage(TemplateView):
    template_name = 'chat_app/index.html'

chat_app/templates/chat_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{% static 'chat_app/css/style.css' %}">
    <title>Movier Chat</title>
</head>
<body>
{% block header %}

{% endblock %}

{% block show_messages %}

{% endblock %}

<script src="{% static 'chat_app/js/script.js'%}"></script>
</body>
</html>

chat_app/templates/chat_app/index.html
{% extends 'chat_app/base.html' %}
{% block header %}
<header class="header">
    <div class="header-wrapper">
       <div class="header-logo">
          <h1>MOVIER</h1>
       </div>
       <div class="auto-block">
          {% if user.is_authenticated %}
          <section class="user">
             <div class="person" id="username">
                   <span>{{user.username}}</span>
                   <a class="user-img" href="#">
                      <svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
                         <title>ionicons-v5-j</title>
                         <path d="M256,48C141.31,48,48,141.31,48,256s93.31,208,208,208,208-93.31,208-208S370.69,48,256,48ZM205.78,164.82C218.45,151.39,236.28,144,256,144s37.39,7.44,50.11,20.94C319,178.62,325.27,197,323.79,216.76,320.83,256,290.43,288,256,288s-64.89-32-67.79-71.25C186.74,196.83,193,178.39,205.78,164.82ZM256,432a175.49,175.49,0,0,1-126-53.22,122.91,122.91,0,0,1,35.14-33.44C190.63,329,222.89,320,256,320s65.37,9,90.83,25.34A122.87,122.87,0,0,1,382,378.78,175.45,175.45,0,0,1,256,432Z"/>
                      </svg>
                   </a>
             </div>
             <div class="exit-btn">
                 <a href="{% url 'users:logout'%}">Выйти</a>
             </div>
          </section>
          {% else %}
          <section class="guest" >
             <div class="auth-btn">
                 <a href="{% url 'users:login_page'%}">Войти</a>
             </div>
          </section>
          {% endif %}
       </div>
    </div>
    </header>
{% endblock %}

{% block show_messages %}
    <div class="chat">
        <div class="messages">
            <div id="chat_log">
            </div>
        </div>
        <div class="input-form">
            <input type="text" class="message_input" name="message_input" placeholder="Введите сообщение:">
            <input type="button"  class="message_btn" name="message_btn" value="Отправить">
        </div>
    </div>
{% endblock %}