chat_app/urls.py
from django.urls import path
from .views import ChatPage

app_name = 'chat_app'

urlpatterns = [
    path('', ChatPage.as_view(), name='chat_page'),
]

movie_service/urls.py
from django.contrib import admin
from django.urls import path, include
from user_app import views as user_views
from rating_app import views as rating_views

from rating_app.views import StartPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', StartPage.as_view(), name='index_page'),
    path('chat/', include('chat_app.urls', namespace='chat')),
    path('users/', include('user_app.urls', namespace='users')),
    path('movies/', include('rating_app.urls', namespace='movies')),
    path('wishlist/', include('wishlist_app.urls', namespace='wishlists'))
]

wishlist_app/urls.py
from django.urls import path
from .views import ChooseMovie, ShowWishlist, AddMovie

app_name = 'wishlist_app'

urlpatterns = [
    path('', ShowWishlist.as_view(), name='list_page'),
    path('add/', AddMovie.as_view(), name='add_page'),
    path('choose/', ChooseMovie.as_view(), name='choose_page'),

]

wishlist_app/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Wish(models.Model):
    kp_id = models.IntegerField(verbose_name='KP-ID')

    poster = models.CharField(max_length=200, verbose_name='Poster')

    title = models.CharField(max_length=50, verbose_name='Title')

    year = models.CharField(max_length=4, verbose_name='Year')

    link = models.CharField(max_length=150, verbose_name='Link')

    kp_rating = models.FloatField(verbose_name='KP-Rating')

    wish_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='user'
    )

    def __str__(self) -> str:
        return f'{self.title}'

wishlist_app/forms.py
from django import forms


class AddForm(forms.Form):
    title = forms.CharField(label='', max_length=100, widget=forms.TextInput(attrs={'class': "form-field",
                                                                                    'placeholder': "Title"}))

wishlist_app/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.db import transaction
from django.views.generic import ListView, FormView, TemplateView

from .models import Wish
from .forms import AddForm
from rating_app.models import Movie
from rating_app.decorators import rate_film_required
from rating_app.utils import get_film_by_id, FILM, get_films_data


# Create your views here.

@method_decorator(login_required(login_url='users:login_page'), name='dispatch')
class ShowWishlist(ListView):
    model = Wish
    template_name = 'wishlist.html'

    def get_queryset(self):
        user = self.request.user
        return Wish.objects.filter(wish_user=user)

    def post(self, request):
        kp_id: int = int(request.POST['film'])
        rating: float = float(request.POST['rating'])
        film: FILM = get_film_by_id(kp_id)

        with transaction.atomic():
            Wish.objects.filter(kp_id=kp_id).delete()
            Movie.objects.create(title=film.ru_name, year=film.year, link=film.year, kp_rating=film.kp_rate,
                                 rating=rating, movie_user=request.user)

        return HttpResponseRedirect(reverse_lazy('wishlists:list_page'))


@method_decorator(login_required(login_url='users:login_page'), name='dispatch')
class AddMovie(FormView):
    form_class = AddForm
    template_name = 'add_movie.html'

    def post(self, request, *args, **kwargs):
        title: str = request.POST['title']
        return HttpResponseRedirect(reverse_lazy('wishlists:choose_page') + f'?title={title}')


@method_decorator(rate_film_required, name='dispatch')
@method_decorator(login_required(login_url='users:login_page'), name='dispatch')
class ChooseMovie(TemplateView):
    template_name = 'select_movie.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        title: str = self.request.GET.get('title')
        context['films_data'] = get_films_data(title)
        return context

    def post(self, request, *args, **kwargs):
        movie_id: int = int(request.POST.get('film'))
        movie_data: FILM = get_film_by_id(movie_id)
        user: str = request.user
        Wish.objects.create(kp_id=movie_id, poster=movie_data.poster_preview, title=movie_data.ru_name,
                            year=movie_data.year, link=movie_data.kp_url,
                            kp_rating=movie_data.kp_rate, wish_user=user)
        return HttpResponseRedirect(reverse_lazy('index_page'))

wishlist_app/templates/wishlist_app/add_movie.html
{% extends 'wishlist_app/base.html' %}
{% load static %}
{% block adding_page %}
<section class="wrapper">
    <h1 class="movie-header">Добавить новый фильм!</h1>
    <form class="create_rating" action="{% url 'wishlists:add_page' %}" method="post">
        {% csrf_token %}
        <div class="range-container">
            {{form}}
        </div>
        <button type="submit">Добавить</button>
    </form>
</section>
{% endblock %}

wishlist_app/templates/wishlist_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{% static 'wishlist_app/css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <title>Movier</title>
</head>
<body>

{% block list_page %}
{% endblock %}

{% block adding_page %}
{% endblock %}

{% block select_page %}
{% endblock %}

<script src="{% static 'js/script.js'%}"></script>
</body>
</html>

wishlist_app/templates/wishlist_app/select_movie.html
{% extends 'wishlist_app/base.html' %}
{% load static %}
{% block select_page %}
<section class="wrapper">
    <h1 class="movie-header">Выберите ваш фильм</h1>
    <a class="go_back" href="{% url 'wishlists:list_page' %}">Назад</a>
    <form class="choose-form" action="{% url 'wishlists:choose_page' %}" method="post">
        {% csrf_token %}
        <div class="main-table">
            <div class="tbl-header">
                <table>
                    <thead>
                        <tr>
                            <th>Постер</th>
                            <th>Фильм</th>
                            <th>Год</th>
                            <th>Ссылка</th>
                        </tr>
                    </thead>
                </table>
            </div>
            <div class="tbl-content">
                <table>
                    <tbody>
                    {% for item in films_data %}
                        <tr>
                            <td>
                                <img src="{{item.poster_preview}}" alt="poster">
                            </td>
                            <td>
                                <input style="display: none;" type="text" name="rating" value="{{rating}}">
                                <input type="radio" name="film" value="{{item.kp_id}}">
                                <label for="film">{{item.ru_name}}</label>
                            </td>
                            <td>{{item.year}}</td>
                            <td><a class="movie-link" href="{{item.kp_url}}">Клик!</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="update-btn">
            <button type="submit">Выбрать</button>
        </div>
    </form>
</section>
{% endblock %}

wishlist_app/templates/wishlist_app/wishlist.html
{% extends 'wishlist_app/base.html' %}
{% load static %}
{% block list_page %}
<section class="wrapper">
    <h1 class="movie-header">Wish List</h1>
    <div class="movie-menu">
        <form action="{% url 'wishlists:list_page' %}" method="GET" class="sorting-form">
            <span>Sorting by: </span>
            <div>
                <ul class="sorting-menu">
                    <li>[ASC]</li>
                    <li><input type="submit" name="title" value="title" class="sort-item"></li>
                    <li><input type="submit" name="year" value="year" class="sort-item"></li>
                </ul>
                <ul class="sorting-menu">
                    <li>[DESC]</li>
                    <li><input type="submit" name="-title" value="title" class="sort-item"></li>
                    <li><input type="submit" name="-year" value="year" class="sort-item"></li>
                </ul>
            </div>
        </form>
        <div>
            <a class="go_back" href="{% url 'index_page' %}">Назад</a>
            <a class="rate_new" href="{% url 'wishlists:add_page' %}">Добавить фильм!</a>
        </div>
    </div>
    <form action="{% url 'wishlists:list_page' %}" method="post">
        {% csrf_token %}
        <div class="main-table">
            <div class="tbl-header">
                <table>
                    <thead>
                        <tr>
                            <th>Постер</th>
                            <th>Фильм</th>
                            <th>Год</th>
                            <th>Ссылка</th>
                        </tr>
                    </thead>
                </table>
            </div>
            <div class="tbl-content">
                <table>
                    <tbody>
                    {% for item in object_list %}
                        <tr>
                            <td><img src="{{item.poster}}" alt="poster"></td>
                            <td>
                                <input class="" type="radio" name="film" value="{{item.kp_id}}">
                                <label for="film">{{item.title}}</label>
                            </td>
                            <td>{{item.year}}</td>
                            <td><a class="movie-link" href="{{item.link}}">Клик!</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="update-btn">
            <div class="update-rating">
                <h3>Choose rating</h3>
                <input name="rating" type="range" value="0" min="0" max="10" step="0.5">
                <div id="h4-container">
                    <div id="h4-subcontainer">
                        <h4>0
                            <span></span>
                        </h4>
                    </div>
                </div>
            </div>
            <button type="submit">Оценить</button>
        </div>
    </form>
</section>
{% endblock %}